
include ../../GNUstep.make

TOOL_NAME := ls.fcgi

$(TOOL_NAME)_OBJC_FILES := AppDelegate.m
$(TOOL_NAME)_C_FILES := main.c
$(TOOL_NAME)_RESOURCE_FILES := error.html
$(TOOL_NAME)_LDFLAGS := -lCGIKit -lMSBooster -ldispatch -lfcgi

include ../../tool.make