
include ../../GNUstep.make

FRAMEWORK_NAME := MSBooster

$(FRAMEWORK_NAME)_NEEDS_GUI := no
$(FRAMEWORK_NAME)_LANGUAGES := en
$(FRAMEWORK_NAME)_HEADER_FILES := MSBooster.h MSBooster_Private.h MSCommon.h MSOCCompatibility.h MSStringConstant.h MSStringManipulation.h
$(FRAMEWORK_NAME)_OBJC_FILES := MSStringManipulation.m
$(FRAMEWORK_NAME)_CURRENT_VERSION_NAME := A
$(FRAMEWORK_NAME)_VERSION := 1.0

include ../../framework.make