
include ../../GNUstep.make

FRAMEWORK_NAME := MSBooster

$(FRAMEWORK_NAME)_NEEDS_GUI := no
$(FRAMEWORK_NAME)_HEADER_FILES := $(wildcard *.h)
$(FRAMEWORK_NAME)_OBJC_FILES := $(wildcard *.m)
$(FRAMEWORK_NAME)_LDFLAGS := -lcrypto -lz -lbz2
$(FRAMEWORK_NAME)_CURRENT_VERSION_NAME := A
$(FRAMEWORK_NAME)_VERSION := 1.0

include ../../framework.make