//
//  NSData+MSTrivialCryptography.h
//  MSBooster
//
//  Created by Maxthon Chan on 9/19/13.
//  Copyright (c) 2013 muski. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <MSBooster/NSData+MSCryptor.h>

@interface NSData (MSTrivialCryptography)

/**
 @brief     A trivial stream cipher.
 
 This cipher is a stream cipher constructed by running SHA-512 HMAC, a keyed
 hash algorithm, in output-feedback mode.
 
 When this method is called on the result of this methhod with the same key, its
 effect is reversed. (i.e. it decrypts itself.)
 
 @warning   There is no guarantee on the strength and effectiveness of this toy
            cipher. Use at your own risk, and use a real cipher on real deals.
            Also, it is quite slow.
 
 @param     key         Cryptography key.
 @param     initializer Initializer
 @param     delegate    Cryptor delegate
 */
- (NSData *)scrambleUsingKey:(NSData *)key initializer:(NSData *)initializer delegate:(id<MSCryptorDelegate>)delegate;

/**
 @brief     A trivial stream cipher.
 
 This cipher is a stream cipher constructed by running SHA-512 HMAC, a keyed
 hash algorithm, in output-feedback mode.
 
 When this method is called on the result of this methhod with the same key, its
 effect is reversed. (i.e. it decrypts itself.)
 
 @warning   There is no guarantee on the strength and effectiveness of this toy
 cipher. Use at your own risk, and use a real cipher on real deals.
 Also, it is quite slow.
 
 @param     key         Cryptography key.
 @param     initializer Initializer
 */
- (NSData *)scrambleUsingKey:(NSData *)key initializer:(NSData *)initializer;

/**
 @brief     Generate a stream of random bytes.
 
 This method reads from /dev/urandom to obtain a stream of random bytes.
 
 @param     length      Length of the data object.
 */
+ (NSData *)randomDataWithLength:(NSUInteger)length;

/**
 Encrypt the key using a random initializer.
 
 The resulting stream will be gzipped binary property list including both data
 and initializer stream.
 */
- (NSData *)scrambleUsingKey:(NSData *)key;

/**
 Encrypt the key using a random initializer.
 
 The resulting stream will be gzipped binary property list including both data
 and initializer stream.
 */
- (NSData *)scrambleUsingKey:(NSData *)key delegate:(id<MSCryptorDelegate>)delegate;

/**
 Decrypt the data generated by scrambleUsingKey: method.
 */
- (NSData *)descrambleUsingKey:(NSData *)key;

/**
 Decrypt the data generated by scrambleUsingKey: method.
 */
- (NSData *)descrambleUsingKey:(NSData *)key delegate:(id<MSCryptorDelegate>)delegate;

@end
